### ISSUE TITLE
which is the format of this Input data set for training?

### ISSUE THREAD

**Issue by xieshenru** [FurkanOM/tf-blazeface#1]
which is the format of this Input data set for training?Can you give the data preparation process?Give an example. Thanks!

**Comment by FurkanOM** [comment]
The data format required for training is the same as the datasets shared [here](https://ibug.doc.ic.ac.uk/resources/facial-point-annotations/). 
However, in some images, you may need to manual label because all faces are not labeled.
Also, you can see some of the images are the same. You should also edit the names of these pictures. For example, image1232_1.jpg, image1232_2.jpg, and corresponding pts files, image1232_1.pts, image1232_2.pts
In addition to these, you may need to collect and label other faces in the wild datasets to more robust the model.
You can use a pre-trained MTCNN to simplify the labeling process.
PS: I do not intend to share the dataset I created using these and similar methods.

**Comment by rose-jinyang** [comment]
Hello
How are you?
Could u explain the dataset's structure in README?
Thanks
